### ISSUE TITLE
Issue in the 'Amount' field validation

### ISSUE THREAD

**Issue by Batman-git-hub** [deepak-shanmugam/InEx-app#1]
**ISSUE 1:** User can successfully create income or expense record with no values given in the 'Amount' field. (So technically It doesn't act as mandatory field)
**ISSUE 2:** After doing the above thing, the value in the 'Amount' is showing as '+.00' for income and '-.00' for expense while viewing the newly created record.

**Comment by deepak-shanmugam** [comment]
This is a valid bug.
Issue 1 screeshot:
![image](https://github.com/deepak-shanmugam/InEx-app/assets/123800750/8a6ac0e6-f521-4075-bb46-837f83c10dcc)
Issue 2 screenshot:
![image](https://github.com/deepak-shanmugam/InEx-app/assets/123800750/cc1bb94e-b585-4bbf-88fd-9d52e745320a)
Thanks for the testing Batman.!

**Comment by deepak-shanmugam** [comment]
RCA: In the scenario of minimum length validation, the amount field validation function returns invalid when length == 0. when user gives enter without entering value to 'amount' field, the length is 1. But the sign(+/-) is always added to 'amount' field before the amount field validation. so the minimum lenth of the 'amount' string is always 1 even when user doesn't enter any value to 'amount' field. So the amount validation function should return Invalid, when length is <= 1.

Issue has been fixed. 

Fix 1 Screenshot: User is restricted to create record if he/she doesn't provide the value in the 'amount' data. As a result, the Issue 2 won't happen.
![image](https://github.com/deepak-shanmugam/InEx-app/assets/123800750/1b84124e-c533-4986-b6f5-f9a52ee73758)
